version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine


  selenium-hub:
    image: selenium/hub:4.13.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.13.0
    # volumes:
    #   - /dev/shm:/dev/shm
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    
  django:
    container_name: django
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tech_news:/usr/src/app/tech_news
      - ./report:/usr/src/app/report
      - ./db.sqlite3:/usr/src/app/db.sqlite3    
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=sjdfiojsdofjijiodsjfioajfio23ojio
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build: 
      context: .
    command: celery --app=tech_news worker -l INFO
    volumes:
      - ./db.sqlite3:/usr/src/app/db.sqlite3    
    #   - ./tech_news:/usr/src/app/tech_news
    #   - ./report:/usr/src/app/report
    environment:
      - DEBUG=1
      - SECRET_KEY=sjdfiojsdofjijiodsjfioajfio23ojio
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery-beat:
    container_name: celery-beat
    build:
      context: .
    command: celery -A tech_news beat -l info
    environment:
      - DEBUG=1
      - SECRET_KEY=sjdfiojsdofjijiodsjfioajfio23ojio
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis      