# version: '3.8'

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis
#       - celery
#       - celery-beat

#   redis:
#     image: redis:alpine

#   celery:
#     build: .
#     command: celery -A tech_news worker --loglevel=info
#     volumes:
#       - .:/code
#     depends_on:
#       - redis

#   celery-beat:
#     build: .
#     command: celery -A tech_news beat --loglevel=info
#     volumes:
#       - .:/code
#     depends_on:
#       - redis
version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tech_news worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tech_news beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7.4.0
