# Generated by Django 5.0.4 on 2024-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('article', models.TextField(max_length=4096, null=True)),
                ('refrence', models.CharField(max_length=512, null=True)),
                ('tags', models.ManyToManyField(to='report.tag')),
            ],
        ),
    ]
