# Generated by Django 5.0.4 on 2024-07-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=models.ManyToManyField(related_name='reports', to='report.tag'),
        ),
    ]
