# Generated by Django 5.0.4 on 2024-07-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
